# Generated by Django 4.2.6 on 2023-10-13 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft_mktplace_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bidder',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='seller',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='buyer',
            field=models.CharField(max_length=100),
        ),
    ]
